"""Generate v8 submission main.py with hardcoded GBM trees."""

import json
import math
from pathlib import Path

model_path = Path(r"C:\Users\anany\NSF project\spectrumx-ai-ran-gary\results\v11_model.json")
out_dir = Path(r"C:\Users\anany\NSF project\spectrumx-ai-ran-gary\submissions\leaderboard_v11")
out_dir.mkdir(parents=True, exist_ok=True)

data = json.loads(model_path.read_text())
trees = data["trees"]
init_log_odds = 0.0  # Prior-corrected for 50/50 test set
lr = data["gbm_learning_rate"]
threshold = 0.5  # Standard threshold with corrected prior
scaler_mean = data["scaler_mean"]
scaler_std = data["scaler_std"]

# Flatten all trees into parallel arrays for compact storage
all_left = []
all_right = []
all_feature = []
all_threshold = []
all_value = []
tree_offsets = [0]

for t in trees:
    n = len(t["feature"])
    all_left.extend(t["children_left"])
    all_right.extend(t["children_right"])
    all_feature.extend(t["feature"])
    all_threshold.extend(t["threshold"])
    all_value.extend(t["value"])
    tree_offsets.append(tree_offsets[-1] + n)

total_nodes = tree_offsets[-1]

lines = []
lines.append('"""')
lines.append("v11 submission: noise-weighted GBM with prior correction.")
lines.append("")
lines.append("Improvements over v9:")
lines.append("- GBM trained with 3x noise sample weight (penalizes false positives)")
lines.append("- Prior-corrected INIT_LOG_ODDS=0 for 50/50 test")
lines.append("- Threshold=0.5 (standard)")
lines.append("- Balanced CV accuracy: 93.1%")
lines.append('"""')
lines.append("")
lines.append("from __future__ import annotations")
lines.append("")
lines.append("from pathlib import Path")
lines.append("")
lines.append("import numpy as np")
lines.append("from scipy import signal as sig")
lines.append("from scipy.stats import kurtosis as scipy_kurtosis, skew as scipy_skew")
lines.append("")
lines.append(f"MAX_IQ_SAMPLES = {data['max_iq_samples']}")
lines.append(f"N_TREES = {len(trees)}")
lines.append(f"LEARNING_RATE = {lr}")
lines.append(f"INIT_LOG_ODDS = {init_log_odds}")
lines.append(f"PROB_THRESHOLD = {threshold}")
lines.append("")

# Emit arrays
def emit_list(name, values, per_line=20):
    lines.append(f"{name} = [")
    for i in range(0, len(values), per_line):
        chunk = values[i : i + per_line]
        lines.append("    " + ", ".join(repr(v) for v in chunk) + ",")
    lines.append("]")

emit_list("TREE_OFFSETS", tree_offsets)
lines.append("")
emit_list("TREE_LEFT", all_left)
lines.append("")
emit_list("TREE_RIGHT", all_right)
lines.append("")
emit_list("TREE_FEATURE", all_feature)
lines.append("")
emit_list("TREE_THRESHOLD", all_threshold)
lines.append("")
emit_list("TREE_VALUE", all_value)
lines.append("")
emit_list("SCALER_MEAN", scaler_mean)
lines.append("")
emit_list("SCALER_STD", scaler_std)

lines.append("")
lines.append("")
lines.append('def _load_iq_auto(filepath: str | Path) -> np.ndarray:')
lines.append('    data = np.load(filepath, mmap_mode="r")')
lines.append("    if np.iscomplexobj(data):")
lines.append("        n = min(MAX_IQ_SAMPLES, data.shape[0])")
lines.append("        return np.array(data[:n], dtype=np.complex64)")
lines.append("    if data.ndim == 2 and data.shape[1] == 2:")
lines.append("        n = min(MAX_IQ_SAMPLES, data.shape[0])")
lines.append("        return (data[:n, 0].astype(np.float32) + 1j * data[:n, 1].astype(np.float32))")
lines.append("    if data.dtype == np.int16 and data.ndim == 1 and data.size % 2 == 0:")
lines.append("        n = min(MAX_IQ_SAMPLES * 2, data.shape[0])")
lines.append("        return (data[:n:2].astype(np.float32) + 1j * data[1:n:2].astype(np.float32))")
lines.append('    raise ValueError(f"Unsupported format: shape={data.shape}, dtype={data.dtype}")')

lines.append("")
lines.append("")
lines.append("def _extract_features(iq: np.ndarray, sample_rate: float = 1e6) -> np.ndarray:")
lines.append("    N = len(iq)")
lines.append("    mag = np.abs(iq)")
lines.append("    power = mag * mag")
lines.append("    mean_power = float(np.mean(power))")
lines.append("")
lines.append("    nperseg = min(8192, N)")
lines.append("    _, psd = sig.welch(")
lines.append('        iq, fs=sample_rate, nperseg=nperseg,')
lines.append('        return_onesided=False, scaling="density",')
lines.append("    )")
lines.append("    psd_mag = np.abs(psd)")
lines.append("    psd_mean = float(np.mean(psd_mag))")
lines.append("    psd_std = float(np.std(psd_mag))")
lines.append("    psd_max = float(np.max(psd_mag))")
lines.append("    psd_min = float(np.min(psd_mag))")
lines.append("")
lines.append("    p10, p25, p75, p90 = np.percentile(psd_mag, [10, 25, 75, 90])")
lines.append("    psd_iqr = float(p75 - p25)")
lines.append("")
lines.append("    psd_pos = psd_mag[psd_mag > 0]")
lines.append("    geo_mean = float(np.exp(np.mean(np.log(psd_pos)))) if psd_pos.size > 0 else 0.0")
lines.append("    flatness = geo_mean / psd_mean if psd_mean > 0 else 0.0")
lines.append("")
lines.append("    psd_sum = np.sum(psd_mag)")
lines.append("    if psd_sum > 0:")
lines.append("        psd_norm = psd_mag / psd_sum")
lines.append("        psd_norm_pos = psd_norm[psd_norm > 0]")
lines.append("        spectral_entropy = float(-np.sum(psd_norm_pos * np.log2(psd_norm_pos)))")
lines.append("    else:")
lines.append("        spectral_entropy = 0.0")
lines.append("")
lines.append("    peak_to_mean = psd_max / (psd_mean + 1e-30)")
lines.append("")
lines.append("    sk_seg_len = 1024")
lines.append("    n_segs = N // sk_seg_len")
lines.append("    if n_segs >= 8:")
lines.append("        iq_trimmed = iq[: n_segs * sk_seg_len].reshape(n_segs, sk_seg_len)")
lines.append("        window = np.hanning(sk_seg_len).astype(np.float32)")
lines.append("        fft_out = np.fft.fft(iq_trimmed * window[np.newaxis, :], axis=1)")
lines.append("        psd_segs = (np.abs(fft_out) ** 2) / (sk_seg_len * sample_rate)")
lines.append("        sk_per_bin = scipy_kurtosis(psd_segs, axis=0, fisher=True)")
lines.append("        spectral_kurt_mean = float(np.mean(sk_per_bin))")
lines.append("        spectral_kurt_max = float(np.max(sk_per_bin))")
lines.append("    else:")
lines.append("        spectral_kurt_mean = 0.0")
lines.append("        spectral_kurt_max = 0.0")
lines.append("")
lines.append("    n_bins = len(psd_mag)")
lines.append("    quarter = n_bins // 4")
lines.append("    total_energy = float(np.sum(psd_mag)) + 1e-30")
lines.append("    band_energies = [")
lines.append("        float(np.sum(psd_mag[i * quarter: (i + 1) * quarter])) / total_energy")
lines.append("        for i in range(4)")
lines.append("    ]")
lines.append("    band_energy_std = float(np.std(band_energies))")
lines.append("")
lines.append("    ac = float(np.abs(np.mean(iq[1:] * np.conj(iq[:-1])))) if N > 1 else 0.0")
lines.append("")
lines.append("    mag_kurtosis = float(scipy_kurtosis(mag, fisher=True))")
lines.append("    mag_skewness = float(scipy_skew(mag))")
lines.append("    crest_factor = float(np.max(mag) / (np.sqrt(mean_power) + 1e-30))")
lines.append("    i_std = float(np.std(iq.real))")
lines.append("    q_std = float(np.std(iq.imag))")
lines.append("    iq_corr = float(np.abs(np.corrcoef(iq.real, iq.imag)[0, 1])) if N > 1 else 0.0")
lines.append("    power_var_ratio = float(np.var(power)) / (mean_power ** 2 + 1e-30)")
lines.append("")
lines.append("    return np.array([")
lines.append("        psd_mean, psd_std, psd_max, psd_min,")
lines.append("        float(p10), float(p25), float(p75), float(p90), psd_iqr,")
lines.append("        flatness, spectral_entropy, peak_to_mean,")
lines.append("        spectral_kurt_mean, spectral_kurt_max,")
lines.append("        band_energies[0], band_energies[1], band_energies[2], band_energies[3],")
lines.append("        band_energy_std, ac,")
lines.append("        mean_power, float(np.std(power)), float(np.std(mag)),")
lines.append("        mag_kurtosis, mag_skewness, crest_factor,")
lines.append("        i_std, q_std, iq_corr, power_var_ratio,")
lines.append("    ], dtype=float)")

lines.append("")
lines.append("")
lines.append("def _predict_gbm(x_scaled: np.ndarray) -> float:")
lines.append("    score = INIT_LOG_ODDS")
lines.append("    for i in range(N_TREES):")
lines.append("        off = TREE_OFFSETS[i]")
lines.append("        node = 0")
lines.append("        while TREE_LEFT[off + node] != -1:")
lines.append("            if x_scaled[TREE_FEATURE[off + node]] <= TREE_THRESHOLD[off + node]:")
lines.append("                node = TREE_LEFT[off + node]")
lines.append("            else:")
lines.append("                node = TREE_RIGHT[off + node]")
lines.append("        score += LEARNING_RATE * TREE_VALUE[off + node]")
lines.append("    return 1.0 / (1.0 + np.exp(-score))")

lines.append("")
lines.append("")
lines.append("def evaluate(filename: str) -> int:")
lines.append("    iq = _load_iq_auto(filename)")
lines.append("    features = _extract_features(iq)")
lines.append("    features = np.nan_to_num(features, nan=0.0, posinf=0.0, neginf=0.0)")
lines.append("")
lines.append("    mean = np.array(SCALER_MEAN)")
lines.append("    std = np.array(SCALER_STD)")
lines.append("    x_scaled = (features - mean) / (std + 1e-30)")
lines.append("")
lines.append("    prob = _predict_gbm(x_scaled)")
lines.append("    return 1 if prob >= PROB_THRESHOLD else 0")

content = "\n".join(lines) + "\n"
(out_dir / "main.py").write_text(content, encoding="utf-8")
print(f"Generated {out_dir / 'main.py'} ({len(content)} bytes, {len(lines)} lines)")

# user_reqs.txt
(out_dir / "user_reqs.txt").write_text("numpy\nscipy\n", encoding="utf-8")
print("Generated user_reqs.txt")
